name: plant_ai
description: "CardamomAI - AI-assisted cardamom disease detection app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.3.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  camera: ^0.11.2+1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  tflite_flutter: ^0.12.1
  image: ^4.0.17
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  google_mobile_ads: ^9.0.0
  share_plus: ^13.3.0
  cross_file: ^0.3.5+2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model/
