// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuT0zwW9MpK4gAuXcrgTH-3GmY2ma6d14',
    appId: '1:707951057817:web:e71c7055f7efef61805108',
    messagingSenderId: '707951057817',
    projectId: 'cardamomai',
    authDomain: 'cardamomai.firebaseapp.com',
    storageBucket: 'cardamomai.firebasestorage.app',
    measurementId: 'G-44BGJY298R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFdg8buB6lvfBX_oVRZmguWrUtGc32QI',
    appId: '1:707951057817:android:3c92b62816907aa8805108',
    messagingSenderId: '707951057817',
    projectId: 'cardamomai',
    storageBucket: 'cardamomai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6t2Vo2sysw7JZKMhzl-H4cnDWoqTDZiM',
    appId: '1:707951057817:ios:b17c492be6821592805108',
    messagingSenderId: '707951057817',
    projectId: 'cardamomai',
    storageBucket: 'cardamomai.firebasestorage.app',
    iosBundleId: 'com.example.plantAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6t2Vo2sysw7JZKMhzl-H4cnDWoqTDZiM',
    appId: '1:707951057817:ios:b17c492be6821592805108',
    messagingSenderId: '707951057817',
    projectId: 'cardamomai',
    storageBucket: 'cardamomai.firebasestorage.app',
    iosBundleId: 'com.example.plantAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuT0zwW9MpK4gAuXcrgTH-3GmY2ma6d14',
    appId: '1:707951057817:web:a415d97ac961d5ff805108',
    messagingSenderId: '707951057817',
    projectId: 'cardamomai',
    authDomain: 'cardamomai.firebaseapp.com',
    storageBucket: 'cardamomai.firebasestorage.app',
    measurementId: 'G-CY3MBGP03X',
  );
}
